d2 = [
    "Brand",
    "no_of_rear_camera",
    "rear_camera_1_pixels",
    "no_of_front_camera",
    "front_camera_1_pixels",
    "Release_year",
    "Screen-size",
    "operationg_system",
    "Internal_storage(GB)",
    "WiFi",
    "Bluetooth",
    "Battery(mah)",
    "RAM",
    "Touchscreen",
    "Form-factor",
    "Processor",
    "GPS",
    "Resolution",
    "Accelerometer",
    "Proximity_sensor",
    "Ambient_light_sensor",
    "Expandable_storage",
    "Rear_flash",
    "Proceesor_make",
    "Height",
    "Breadth",
    "Width",
    "Weight",
    "Compass/magnetometer",
    "Headphones",
    "Gyroscope",
    "Expandable_storage_type",
    "4G_or_3G",
    "Simtype",
    "GSM/CDMA",
    "Expandable_storage(GB)",
]
values = {
    "no_of_rear_camera": 2,
    "rear_camera_1_pixels": 27,
    "no_of_front_camera": 1,
    "front_camera_1_pixels": 12,
    "Release_year": 2019,
    "Screen-size": 6,
    "Internal_storage(GB)": 128,
    "Battery(mah)": 5000,
    "RAM": 4096,
    "Resolution": 1080,
    "Height": 153,
    "Breadth": 74,
    "Width": 8.9,
    "Price_in_India": 17904,
    "Weight": 188,
    "Expandable_storage(GB)": 128,
    "operationg_system": "Android",
    "WiFi": "Yes",
    "Bluetooth": "Yes",
    "Touchscreen": "Yes",
    "Form-factor": "Touchscreen",
    "Processor": "octa-core",
    "GPS": "Yes",
    "Accelerometer": "Yes",
    "Proximity_sensor": "Yes",
    "Ambient_light_sensor": "Yes",
    "Expandable_storage": "Yes",
    "Rear_flash": "Yes",
    "Proceesor_make": "Qualcomm Snapdragon",
    "Compass/magnetometer": "Yes",
    "Headphones": "Yes",
    "Gyroscope": "Yes",
    "Expandable_storage_type": "microSD",
    "4G_or_3G": "4G",
    "Simtype": "Nano-SIM",
    "GSM/CDMA": "GSM",
}
brandvals = [
    "10.or",
    "Acer",
    "Adcom",
    "Airtel",
    "Alcatel",
    "Alpha",
    "Amazon",
    "Apple",
    "Archos",
    "Asus",
    "AOC",
    "Billion",
    "Black Shark",
    "BlackBerry",
    "Blu",
    "BQ",
    "Cat",
    "Celkon",
    "Centric",
    "Cherry Mobile",
    "Comio",
    "Coolpad",
    "Datawind",
    "Detel",
    "Dizo",
    "Docoss",
    "Doogee",
    "Energizer",
    "Elephone",
    "Elari",
    "Essential",
    "Evercoss",
    "Fairphone",
    "Fly",
    "Gionee",
    "General Mobile",
    "Gionee",
    "Google",
    "Hisense",
    "Homtom",
    "HP",
    "HTC",
    "Huawei",
    "Hyve",
    "Idea",
    "iBall",
    "iBerry",
    "i-mobiles",
    "iQOO",
    "iVoomi",
    "Itel",
    "Jio",
    "Jivi",
    "Jio",
    "Karbonn",
    "Kestrel",
    "Kodak",
    "Kult",
    "Kyocera",
    "Land Rover",
    "Lava",
    "LeEco",
    "Leica",
    "Lephone",
    "Lenovo",
    "Letv",
    "LG",
    "Lyf",
    "Lumigon",
    "Mafe Mobile",
    "MarQ by Flipkart",
    "Marshall",
    "Maxx Mobile",
    "Mobiistar",
    "Mitashi",
    "Microsoft",
    "Mito",
    "Motorola",
    "MTS",
    "MyPhone",
    "Namotel",
    "Neffos",
    "Nextbit",
    "Nexian",
    "Nokia",
    "Nubia",
    "Nuu Mobile",
    "Oplus",
    "Oppo",
    "Obi",
    "Obi Worldphone",
    "Onida",
    "OnePlus",
    "Oukitel",
    "Panasonic",
    "Pepsi",
    "Philips",
    "Phicomm",
    "Poco",
    "Polaroid",
    "Porsche Design",
    "QMobile",
    "QiKU",
    "Razer",
    "Reach",
    "Realme",
    "Redmi",
    "Reliance",
    "Ringing Bells",
    "Rio",
    "Royole",
    "Salora",
    "Samsung",
    "Saygus",
    "Sharp",
    "Silent Circle",
    "Sikur",
    "Sirin",
    "Smartisan",
    "Smartron",
    "Sony",
    "Spice",
    "Sunstrike",
    "Symphony",
    "Tambo",
    "TCL",
    "Tecno",
    "Tonino Lamborghini",
    "Turing",
    "Umi",
    "Umidigi",
    "Unihertz",
    "Vaio",
    "Vertu",
    "Videocon",
    "Viaan",
    "Wangapally",
    "Wickedleak",
    "Wiio",
    "Xiaomi",
    "Xolo",
    "Yamada Denki",
    "Yandex",
    "Yu",
    "Zen",
    "Ziox",
    "Zopo",
    "ZTE",
    "Zuk",
    "None",
]
osvals = [
    "Android",
    "iOS",
    "HarmonyOS",
    "Cyanogen",
    "Windows",
    "Nokia",
    "Tizen",
    "Proprietary",
    "Flyme",
    "Ubuntu",
    "OxygenOS",
    "BlackBerry",
    "Series",
    "Firefox",
    "Sailfish",
    "Feature",
    "KAI",
    "Fire",
    "Silent",
    "Granite",
    "Symbian",
]
ffvals = ["Touchscreen", "Swivel", "Foldable", "Bar", "QWERTY", "Flip", "Slider"]
pvals = [
    "octa-core",
    "quad-core",
    "hexa-core",
    "deca-core",
    "dual-core",
    "one-core",
    "e",
]
pmvals = [
    "Qualcomm Snapdragon",
    "MediaTek Dimensity",
    "MediaTek Helio",
    "Apple A13",
    "MediaTek",
    "Google",
    "Samsung Exynos",
    "HiSilicon Kirin",
    "Apple A15",
    "Apple A11",
    "Apple A12",
    "Apple A14",
    "Qualcomm",
    "Intel Atom",
    "Snapdragon 8",
    "Apple A16",
    "Spreadtrum Shark",
    "Spreadtrum",
    "Unisoc",
    "Snapdragon 7+",
    "Apple",
    "Speadtrum",
    "Broadcom",
    "Apple A10",
    "ARM",
    "Leadcore",
    "Xiaomi Surge",
    "Spreadtrum SC9820A",
    "Google Tensor",
    "LG",
    "Unisoc T618",
]
